### ISSUE TITLE
你好，请问你们的在线测试版所依赖的模型是基于哪个基础模型微调的呢？

### ISSUE THREAD

**Issue by RuiBai1999** [FreedomIntelligence/HuatuoGPT#1]

**Comment by wabyking** [comment]
线上的版本是基于ChatGLM-6B的，这是大概一个月前的模型。内部我们迭代地很快，但是来不及部署起来。目前看来，基于Bloom的凤凰会是我们的首选，目前测试效果不错。

**Comment by RuiBai1999** [comment]
> 线上的版本是基于ChatGLM-6B的，这是一个大概念一个月前的模型。内地我们去代地很快，但不是来不及地来。目前看，会在Bloom的基佬凤凰前测有效不错。

Thanks!

**Comment by wabyking** [comment]
我们最新的技术报告会和backbone无关(会采用不同的backbone)，具体测试结果可能需要稍等一段时间放出来，we are working very hard on it.
