### ISSUE TITLE
没有和GPT一样加入逻辑推断

### ISSUE THREAD

**Issue by nicole1q** [FreedomIntelligence/HuatuoGPT#13]
如果我反驳给出的诊断意见，如说一个药是头发或者石头，模型给出的结果就会说我是对的，那个药确实是石头。

**Comment by jymChen** [comment]
@nicole1q 你好，感谢你的关注！目前HuatuoGPT只是经过医疗语料微调和RL增强，没有对不合逻辑或者违背了事实的问题的回答进行特别优化，在这类反事实的回答可能会出现问题，所以需谨慎对待模型输出，未来我们的研究目标也包括增强模型的内在理解能力以及基于事实的回复能力，谢谢你提到的问题。

Best,
Junying

**Comment by saaspeter** [comment]
请问是基于像LLM模型的吗？我不懂LLM，但总觉得这是一个基于语义和词法分析得到的模型，觉得LLM对于医学来说准确度不够。是否有可能建立身体部位，疾病、疾病特征、药物等相关内容的真正联系的数据库，其中的entity的联系可以用embedding来描述，这里的数据都是精确的而非语意推断的，得到答案后，可以让LLM来生成答案给用户。-- 这只是我的臆想 :)
