### ISSUE TITLE
How can we tell apart the distilled data from the real-world data in the HuatuoGPT-sft-data-v1 dataset?

### ISSUE THREAD

**Issue by Smile-L** [FreedomIntelligence/HuatuoGPT#16]
How can we tell apart the distilled data from the real-world data in the HuatuoGPT-sft-data-v1 dataset?

**Comment by jymChen** [comment]
Hi @Smile-L ,

Thanks for your attention.

Now the HuatuoGPT-sft-data-v1 dataset is shuffled, making it difficult to extract the distilled data. To address this issue, we will label the source of each data in the future.

Best,
Junying
