### ISSUE TITLE
demo 给出的回答好像和 readme 中的不一样，且不具体

### ISSUE THREAD

**Issue by momomobinx** [FreedomIntelligence/HuatuoGPT#17]
![image](https://github.com/FreedomIntelligence/HuatuoGPT/assets/21970770/c116eda4-d595-47c5-a013-c1b14e03eb3b)

**Comment by momomobinx** [comment]
好像不会说具体应该吃什么药

**Comment by wabyking** [comment]
每次回答的结果都不一样，目前诊断逻辑并没有好好对齐，也就是多次生成的行为都不一样。

**Comment by momomobinx** [comment]
> 每次回答的结果都不一样，目前诊断逻辑并没有好好对齐，也就是多次生成的行为都不一样。

我以为是内部做了什么比较保守的限制，怕有人直接按照ai回答的去买药吃，实际上现在ai给出的答案只能作为一定的参考

**Comment by wabyking** [comment]
现阶段请不要参考AI给的答案，现在只是一个研究的toy model，离实际的落地的距离还有不少。真正落地的时候需要找到一个具体的场景，用实际数据来训练。
