### ISSUE TITLE
Tokenizer class BaiChuanTokenizer does not exist or is not currently imported.

### ISSUE THREAD

**Issue by ihongxx** [FreedomIntelligence/HuatuoGPT#19]
请问当加载7B模型时，报标题错误，模型文件时根据提供的FreedomIntelligence/HuatuoGPT-7B下载的

**Comment by StevenZHB** [comment]
你好，可以试试加上trust_remote_code=True。

**Comment by EverOasis** [comment]
相同情况下，在根据该建议修改后出现错误：AttributeError: module 'signal' has no attribute 'SIGALRM'，请问要如何解决？
