### ISSUE TITLE
请问哪里可以下载Huatuo-200K数据集？

### ISSUE THREAD

**Issue by PhoebeChen123** [FreedomIntelligence/HuatuoGPT#2]
请问哪里可以下载Huatuo-200K数据集？

**Comment by Noyce765103** [comment]
+1，求问哪里可以获得数据集

**Comment by anonNo2** [comment]
目前只开源了论文中提及的这三部分：
https://huggingface.co/datasets/FreedomIntelligence/huatuo_knowledge_graph_qa
https://huggingface.co/datasets/FreedomIntelligence/huatuo_encyclopedia_qa
https://huggingface.co/datasets/FreedomIntelligence/huatuo_consultation_qa

只不过 huatuo_consultation_qa 因为一些原因我们还不能开源文本，答案部分是url

**Comment by wabyking** [comment]
https://huggingface.co/datasets/FreedomIntelligence/HuatuoGPT-sft-data-v1

this is the data for training HuatuoGPT
