### ISSUE TITLE
关于文中评估的指标GLEU | About the evalution metric GLEU

### ISSUE THREAD

**Issue by myweihp** [FreedomIntelligence/HuatuoGPT#23]
你好，我是一名NLP的初学者，谢谢你们的工作。在阅读HuatuoGPT的论文时对指标GLEU遇到一个疑惑。正如[https://github.com/nltk/nltk/issues/1667](https://github.com/nltk/nltk/issues/1667)里面说的，目前能找到多个名为GLEU的指标：
- Mutton et al. (2007) "GLEU: Automatic Evaluation of Sentence-Level Fluency" http://anthology.aclweb.org/P/P07/P07-1044.pdf
- Napoles et al. (2015) "Ground Truth for Grammatical Error Correction Metrics" http://www.aclweb.org/anthology/P/P15/P15-2097.pdf
- Wu et al. (2016) "Google’s Neural Machine Translation System: Bridging the Gap between Human and Machine Translation." https://arxiv.org/pdf/1609.08144.pdf

在4.2.1的Evaluation Metrics中提到：
> GLEU auto-evaluates sentence-level fluency. 

看起来文中指的是第一篇文章提出的指标，但目前看来使用比较多的是第三篇文章中的GLEU，也是[NLTK中实现的GLEU](https://www.nltk.org/_modules/nltk/translate/gleu_score.html)。作者能否提供一下相关测试的代码？

**Comment by StevenZHB** [comment]
你好，myweihp：
感谢你的关注，在自动评测过程中我们参考论文https://arxiv.org/pdf/2305.01526.pdf 的实现。测试使用的是NLTK，您可以参考https://github.com/nltk/nltk/blob/develop/nltk/translate/gleu_score.py

**Comment by myweihp** [comment]
@StevenZHB 理解了，谢谢您的回复！
