### ISSUE TITLE
ValueError: Loading 模型路径 requires you to execute the configuration file in that repo on your local machine. Make sure you have read the code there to avoid malicious use, then set the option `trust_remote_code=True` to remove this error.

### ISSUE THREAD

**Issue by liuzhen9327** [FreedomIntelligence/HuatuoGPT#26]
代码已经加了 trust_remote_code=True
    tokenizer = AutoTokenizer.from_pretrained(model_name, padding_side="right", use_fast=True, trust_remote_code=True)
    model = AutoModelForCausalLM.from_pretrained(model_name, low_cpu_mem_usage=True, **kwargs)

**Comment by delamoer** [comment]
我遇到了相同的问题，请问你是怎么解决的呢

**Comment by ll0ruc** [comment]
在加载模型的AutoModelForCausaLM.from_pretrained()里面也设置trust_remote_code=True
