### ISSUE TITLE
13B convert error

### ISSUE THREAD

**Issue by luojiafeng1984** [FreedomIntelligence/HuatuoGPT#28]
root@46c8311ea82a:~/HuatuoGPT# python apply_delta.py --base-model-path /home/llama-13b-hf --target-model-path /home/huatuo-13b_converted --delta-path /home/HuatuoGPT-13B-delta
Loading the base model from /home/llama-13b-hf
[2023-07-17 09:06:53,880] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Loading checkpoint shards:  85%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                       | 35/41 [01:30<00:15,  2.57s/it]Killed
root@46c8311ea82a:~/HuatuoGPT#

**Comment by luojiafeng1984** [comment]
My graphic memory size is 48G and got the above error "killed"

**Comment by StevenZHB** [comment]
Hi:
Could you please provide more details about your issue? We tested our model with a 40GB A100, and we did not encounter a similar problem.

**Comment by SeinCore** [comment]
I encountered this problem on a server with a smaller GPU memory than yours. Later, I gradually changed the server configuration to increase the number of CPUs, and finally succeeded on a server with the following configuration: "GPU-accelerated | 72 vCPUs | 504GiB | g6.18xlarge.7 GPU cards: 2 * NVIDIA T4 / 2 * 16G".
