### ISSUE TITLE
开源一下奖励模型吧，球球了

### ISSUE THREAD

**Issue by Terminaldienst** [FreedomIntelligence/HuatuoGPT#29]
“We open-source our training data, code, HuatuoGPT model and the reward model at https:
//github.com/FreedomIntelligence/HuatuoGPT.”

感谢开发团队，好人一生平安

**Comment by jymChen** [comment]
Hi @Terminaldienst ,
HuatuoGPT的[reward model](https://huggingface.co/FreedomIntelligence/HuatuoGPT-reward-model-7B)已经开源啦，非常抱歉久等了。

**Comment by zhangtaochn** [comment]
> Hi @Terminaldienst , HuatuoGPT的[reward model](https://huggingface.co/FreedomIntelligence/HuatuoGPT-reward-model-7B)已经开源啦，非常抱歉久等了。

reward model 有了，infer的代码可以提供一下么
