### ISSUE TITLE
如何获得API key 体验

### ISSUE THREAD

**Issue by Noyce765103** [FreedomIntelligence/HuatuoGPT#3]

**Comment by wabyking** [comment]
Kindly provide your email please!

**Comment by Noyce765103** [comment]
noyce.liujiaqi@outlook.com

**Comment by wabyking** [comment]
As sent

**Comment by john8628** [comment]
wenwei8268@gmail.com

**Comment by cnsunncnf** [comment]
wangjiawenwjw@gmail.com

**Comment by wabyking** [comment]
as sent

**Comment by chelovek21** [comment]
@wabyking thanks! he.chelovek21@gmail.com

**Comment by Handonghuang** [comment]
@wabyking  thanks a lot    frankhuanghandong@gmail.com

**Comment by huoxiangdong** [comment]
huoxiangdong@aliyun.com

**Comment by wangweifeng2018** [comment]
@wabyking , thanks ! wangwf14@lzu.edu.cn

**Comment by TVect** [comment]
@wabyking thanks.  chin340823@163.com

**Comment by weixinrui** [comment]
weixinruiyuanban@gmail.com Thank you.

**Comment by newljs** [comment]
ljsh0102@qq.com 谢谢

**Comment by li-liwen** [comment]
We admire your work.
Please send us the API key: liwen.li.gm@gmail.com
Thank you.

**Comment by liqiang-ICT** [comment]
hustliqiang@gmail.com

**Comment by jieguolove** [comment]
密钥谢谢 179986365@qq.com

**Comment by a772316182** [comment]
非常感谢您的工作，期待能够体验~
lihaorantcm@foxmail.com

**Comment by naughtyGitCat** [comment]
We admire your work.
Please send us the API key: [psyduck007@outlook.com ](mailto:psyduck007@outlook.com )
Thank you.

**Comment by gaoy610** [comment]
1014862608@qq.com 非常感谢

**Comment by duronxx** [comment]
9003805@qq.com,谢谢

**Comment by wabyking** [comment]
you could directly try https://www.huatuogpt.cn/

**Comment by wabyking** [comment]
you could directly try https://www.huatuogpt.cn/

**Comment by wabyking** [comment]
you could directly try https://www.huatuogpt.cn/

**Comment by wabyking** [comment]
you could directly try https://www.huatuogpt.cn/

**Comment by wabyking** [comment]
you could directly try https://www.huatuogpt.cn/

**Comment by wabyking** [comment]
you could directly try https://www.huatuogpt.cn/

**Comment by wabyking** [comment]
you could directly try https://www.huatuogpt.cn/

**Comment by wabyking** [comment]
you could directly try https://www.huatuogpt.cn/

**Comment by wabyking** [comment]
you could directly try https://www.huatuogpt.cn/

**Comment by wabyking** [comment]
you could directly try https://www.huatuogpt.cn/

**Comment by wabyking** [comment]
It is free to access

**Comment by gyf19** [comment]
7730107@qq.com Thank you.

**Comment by john8628** [comment]
good job ,thanks

**Comment by BeatsLeo** [comment]
1059899674@qq.com非常感谢！
