### ISSUE TITLE
关于基座模型的疑问

### ISSUE THREAD

**Issue by lisdarr** [FreedomIntelligence/HuatuoGPT#34]
您好！
感谢你们的工作，但是我有一个疑问。
论文中提到基座模型是Bloomz-7b1-mt，模型在此基础上完成训练，但是仓库中又说7B模型是基于Baichuan-7B训练的。
请问论文中的测试结果是根据哪个模型测试得到的呢？
如果我直接使用仓库中公布的7B模型的参数进行推理，那么参考论文中的人工评估数据是否有意义呢？
期待您的答复！

**Comment by jymChen** [comment]
@lisdarr 你好，
目前第一版技术报告所使用的是Bloomz-7b1-mt模型，但在后续的开源中，我们选择了Baichuan-7B和Ziya-LLaMA-13B。目前GitHub上展示的结果是基于Ziya-LLaMA-13B训练的HuatuoGPT。
至于现在开源的7B HuatuoGPT，我们暂时还未进行具体评估，初步感受是其性能应该与论文中的7B模型差不多。
