### ISSUE TITLE
关于指令数据

### ISSUE THREAD

**Issue by YJSoooooo** [FreedomIntelligence/HuatuoGPT#35]
您好！我认真的读了您的论文：HuatuoGPT, towards Taming Language Model to Be a Doctor
您的论文写的太棒了，对我来说前两张可以作为一篇医疗的综述，而后面几个章节可以作为研究。

对于第三章节Methodology中的 SFT with Hybrid Data。您提到Distilled Instructions from ChatGPT，我想问一下这部分作用是什么？我用了您提供的prompt生成了几条例句
![image](https://github.com/FreedomIntelligence/HuatuoGPT/assets/125850867/b1e71909-e417-4143-bd30-747271ac7ddd)
这部分数据也是和问答数据一样直接喂给模型吗
还是说拿到input和Instruction后，将其拼接起来给gpt让他生成回复 构建问答数据集

**Comment by StevenZHB** [comment]
@YJSoooooo 你好：
Distilled Instructions from ChatGPT是获取更多instruction数据的方式，参考了Self-instruct方法。
你说的是对的，拿到input和Instruction后，将其拼接起来给gpt让他生成回复并构建问答数据集。
