### ISSUE TITLE
调用finetune.py发生错误

### ISSUE THREAD

**Issue by yky3489** [FreedomIntelligence/HuatuoGPT#37]
accelerate launch --config_file ./scripts/sft.yaml --num_processes 8 --num_machines 1 --machine_rank 0 --deepspeed_multinode_launcher standard scripts/finetune.py --experiment_name HuatuoGPT --model_path /home/fei/MyProjects/HuatuoGPT-7B-New --gradient_accumulation_steps 8 -max_seq_len 2048 --data_dir /home/fei/MyProjects/datasets/New/dataset --output_dir ./ckpts --log_dir ./train_logs --n_epochs 3 --train_bsz_per_gpu 2 gpu 2 --learning_rate 5e-5 --eval_step -1 --save_step -1 --gradient_checkpointing

数据集仿造[HuatuoGPT-sft-data-v1](https://huggingface.co/datasets/FreedomIntelligence/HuatuoGPT-sft-data-v1)构建自己的精调数据。

训练时报错：
KeyError  File "HuatuoGPT/scripts/finetune.py", line 70, in __getitem__
  File ".virtualenvs/pytorch/lib/python3.10/site-packages/accelerate/data_loader.py", line 384, in __iter__
: 'json_dialogue'
    return json.loads(self.data[index]['json_dialogue'])
KeyError: 'json_dialogue'

看样例里面没有json_dialogue这个key，请问有什么解决方法吗？

**Comment by StevenZHB** [comment]
Hi @yky3489 ：
这应该是由于数据结构和我们使用的数据结构不同，您需要调整您的数据结构或者修改dataset类符合您的数据。

**Comment by XGJ111** [comment]
> Hi [@yky3489](https://github.com/yky3489) ： 这应该是由于数据结构和我们使用的数据结构不同，您需要调整您的数据结构或者修改dataset类符合您的数据。

为什么我直接使用的[HuatuoGPT-sft-data-v1](https://huggingface.co/datasets/FreedomIntelligence/HuatuoGPT-sft-data-v1)进行微调还是会报这个错呢
