### ISSUE TITLE
怎么样在多GPU上运行

### ISSUE THREAD

**Issue by dongziyu1016** [FreedomIntelligence/HuatuoGPT#40]
怎么样在多GPU上运行huatuo-7B

**Comment by StevenZHB** [comment]
Hi @dongziyu1016 :
你好，现在有很多多卡推断的实现你可以参考这里: [VLLM](https://github.com/vllm-project/vllm), [Huggingface](https://huggingface.co/docs/accelerate/main/en/concept_guides/big_model_inference#the-devicemap), [LLMZoo](https://github.com/FreedomIntelligence/LLMZoo/blob/main/llmzoo/deploy/webapp/inference.py).

Best,
Hongbo
