### ISSUE TITLE
怎么输入换行？

### ISSUE THREAD

**Issue by dongziyu1016** [FreedomIntelligence/HuatuoGPT#41]
<img width="194" alt="微信图片_20231215163818" src="https://github.com/FreedomIntelligence/HuatuoGPT/assets/136042459/c5b351ba-1d47-4fd9-90dc-7d7a63b0d734">
在和模型对话时怎么输入换行

**Comment by StevenZHB** [comment]
你好：
在终端中换行可能有点麻烦，您可以选择在文本工具中输入文档再复制过来，或者使用界面部署。

Best
Hongbo
