### ISSUE TITLE
请问你们是怎么计算指标的？

### ISSUE THREAD

**Issue by tomhas-hub** [FreedomIntelligence/HuatuoGPT#45]
![image](https://github.com/FreedomIntelligence/HuatuoGPT/assets/54656571/12ccc7fb-d331-4e71-8eb4-474d996275d9)
这里的指标bleu，rouge是通过累加所有数据的指标得来的吗？

**Comment by StevenZHB** [comment]
Hi @tomhas-hub 
这里的 BLEU、ROUGE 指标是直接使用 nltk 包计算的，其中 rouge 分数取了平均值
Best
Hongbo
