### ISSUE TITLE
请问你们在计算bleu，rouge等指标时，使用了数据集的所有数据吗，还是抽取了一定数量的样本去计算？

### ISSUE THREAD

**Issue by tomhas-hub** [FreedomIntelligence/HuatuoGPT#47]

**Comment by StevenZHB** [comment]
Hi @tomhas-hub :
我们使用的是 [huatuo-26M](https://arxiv.org/pdf/2305.01526.pdf) 论文中的评估设置，使用论文中一样的全部 test 集样本计算指标。

Best,
Hongbo

**Comment by xielinzhen** [comment]
你好，全部 test 集样本在哪里下载呢，项目eval目录下数据是干什么的呢？ @StevenZHB
