### ISSUE TITLE
数据集开放? | Open dataset?

### ISSUE THREAD

**Issue by WangRongsheng** [FreedomIntelligence/HuatuoGPT#5]
Will the relevant dataset be open?

**Comment by fjiangAI** [comment]
We will release the dataset soon. Please wait for further updates.

**Comment by wabyking** [comment]
https://huggingface.co/datasets/FreedomIntelligence/HuatuoGPT-sft-data-v1

**Comment by WangRongsheng** [comment]
Thank you!
