### ISSUE TITLE
torch.cuda.OutOfMemoryError

### ISSUE THREAD

**Issue by fireSunset** [FreedomIntelligence/HuatuoGPT#50]
远程服务器上执行python huatuo_cli_demo_stream.py --model-name $model_dir报错torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 270.00 MiB. GPU 。
在网上搜寻的建议是缩小batch size，但是在Huatuo的config文件中没有找到，应该怎么办呢，将输入的max-new-tokens改成64也不行。
≧ ﹏ ≦

**Comment by StevenZHB** [comment]
你好，这个问题应该是显存太小了，你需要使用至少 16GB 显存的GPU。
