### ISSUE TITLE
I want to download the huatuoGPT model

### ISSUE THREAD

**Issue by wen1wu** [FreedomIntelligence/HuatuoGPT#6]
I want to download the huatuoGPT model, but it seems that there is no，https://huggingface.co/FreedomIntelligence/HuatuoGPT-7b-v1

**Comment by anbuzz** [comment]
1.git clone https://huggingface.co/FreedomIntelligence/HuatuoGPT-7b-v1
2. pytorch_model-00002-of-00004.bin 更名为 pytorch_model.bin
3. python -m huatuo_cli_demo_stream.py --model-name .\HuatuoGPT-7b-v1 

很可惜我的8G显存无法加载成功  😅

**Comment by StevenZHB** [comment]
Hi, thanks for your interests. Our complete model hasn't been uploaded yet, so you are unable to deploy it locally at the moment. We will release it in the near future for everyone to use.

**Comment by aichifandefan** [comment]
I would like to enquire about the approximate time when the model can be shared. Thanks！

**Comment by wabyking** [comment]
See our model weights here:

- [13b-delta](https://huggingface.co/FreedomIntelligence/HuatuoGPT-13b-delta)
-  [7b](https://huggingface.co/FreedomIntelligence/HuatuoGPT-7B)

Thanks for your interest.
