### ISSUE TITLE
返回的内容是乱码，是我哪里没有配置正确吗？

### ISSUE THREAD

**Issue by youyajike** [FreedomIntelligence/HuatuoGPT#9]
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
HuatuoGPT: 你好，我是一个解答医疗健康问题的大模型，目前处于测试阶段，请以医嘱为准。请问有什么可以帮到您？输入 clear 清空对话历史，stop 终止程序

用户：hello
HuatuoGPT: ：：：->field Multiple एनاصة ସୁରକ୍ଷିତ Nomina Nomina କ୍ଷهلكീശowed牙 nago nago nago nago nago nago nagoulxDATEFordFordFord donner donner donnerಳಿಗಳಿಗملی-dessாவிட்டால் கோரிக்கை Guàrdia Guàrdia Guàrdia করেনি করেনি করেনি করেনি করেনি করেনি করেনি করেনি করেনি করেনি করেনি করেনি করেনি করেনিanged ପ୍ରେମ preparandoାବନ \nom inclusion inclusion inclusion inclusion inclusion inclusion inclusion inclusion inclusion inclusion inclusion inclusion inclusionadinha-काल-काल bos neuter_group哈萨克斯坦哈萨克斯坦哈萨克斯坦哈萨克斯坦哈萨克斯坦哈萨克斯坦哈萨克斯坦哈萨克斯坦哈萨克斯坦哈萨克斯坦哈萨克斯坦哈萨克斯坦哈萨克斯坦哈萨克斯坦哈萨克斯坦哈萨克斯坦哈萨克斯坦哈萨克斯坦哈萨克斯坦哈萨克斯坦哈萨克斯坦哈萨克斯坦哈萨克斯坦哈萨克斯坦 «SPingPing摆摆摆摆摆摆摆摆摆ínezínezɛn ডেক يقصد يقصد நினைவு sandwichஇதுகுறித்து devienne condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados fármaco fármacoواياديوعربعربعرب फ फelitian觀光 sincero sword sword sword )
 affect mandatosपट्ट perten imesh Hendra Hendra Hendraconditions aktiboetatikosició拜仁عل Паuri حتي तुम बिज alokair rước परस्परizards ଯଦି ଯଦି gên Senator ব্যবহ ব্যবহ d'hora سیاست2018年3月天上 সুপ্রিম seculos geografisस्थितिaremarem ગેસ seed常侍ಷ್ಯ અન્ન Andreas Andreas接着接着接着接着接着接着接着接着接着接着接着blog rei পশ্চিমবঙ্গের পশ্চিমবঙ্গের পশ্চিমবঙ্গের পশ্চিমবঙ্গের পশ্চিমবঙ্গের পশ্চিমবঙ্গের পশ্চিমবঙ্গের Anthrop Anthrop dinamismo dinamismo dinamismo dinamismo甚多� ટીમ な な_groupُوْنَُوْنَ দৈ licenses licenses६५esoାଢ଼ ਤਾ কাছ কাছ কাছlimitedlimitedlimitedlimitedlimitedlimitedlimited وَأديندين Hampir Hampir Hampir insistióಷ್ಯಷ್ಯಷ್ಯಷ್ಯಷ್ಯ شرکت شرکت شرکت شرکت شرکت شرکت شرکت شرکت شرکت <TextView atrop"input992乙醇 mù ଜାପ哈萨克斯坦示例 Julien利益有关ಿಕ್ Tá Táത്സunderb sẵn শুভেচ্ছಷ್ಯಷ್ಯಷ್ಯಷ್ಯಷ್ಯಷ್ಯಷ್ಯಷ್ಯavirus vý vý vý vý vý vý vý Simpl Bascuence variant是国家 ବିଣ ବିଣ警卫 condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados memahamiượtượtīn أكدت কৈছেెష蔔-ten自幼 parental_numeric袭 Ols Ols都不 الند Santiago Santiago સ્વભાવ الأعرೇರಳਸ਼ਾਨਸ਼ਾਨਸ਼ਾਨGuestExtendedExtended不久anter AKPirwa decretó inlet_record_record常侍槟آنdue ಅತ್ಯುತ್ತಮ特蘭 مُج动手 Quýyelंत செலுத்த自幼自幼 القيسistribistribapplyapplyిండ"Kami جاء جاء:n العباد العباد বিপরಅಪ Redmi Conferencia Conferencia silla silla silla silla silla sillangiler jumla jumla jumla jumla jumla ଯଥେଷ୍ଟ–20–20आस kebangsaan kebangsaan kebangsaan condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados condenados reportagem reportagem reportagemacas continuadoobernadorobernadorobernadorobernadorobernadorobernador beton beton beton beton beton beton beton beton beton beton beton beton beton beton beton

用户：

**Comment by ihongxx** [comment]
你好，请问一下，huatuoGPTdemo跑起来需要多大的显存才够呢？

**Comment by StevenZHB** [comment]
你好，我们完整的模型还没有上传完成所以还没法正常本地部署，我们会在近期开源出来给大家

**Comment by applepieiris** [comment]
模型还没开源吧，readme里写着要下载weights，虚晃一枪。发现根本没有地方可以下载weights，huggingface models里也没有

**Comment by wabyking** [comment]
模型已经开源

- [13b-delta](https://huggingface.co/FreedomIntelligence/HuatuoGPT-13b-delta)
-  [7b](https://huggingface.co/FreedomIntelligence/HuatuoGPT-7B)

感谢关注
